import { defineConfig } from '@playwright/test';

/**
 * E2E: the built app in Chromium with software WebGL2, against the synthetic
 * fixture terrain. No network. Run `bun run build` first; the fixture tiles
 * are generated by the global setup.
 */
export default defineConfig({
  testDir: '.',
  testMatch: /.*\.spec\.ts/,
  globalSetup: './global-setup.ts',
  timeout: 120_000,
  expect: { timeout: 30_000, toHaveScreenshot: { maxDiffPixelRatio: 0.02 } },
  fullyParallel: false,
  workers: 1,
  retries: 0,
  reporter: process.env.CI ? [['list'], ['html', { open: 'never', outputFolder: '../../playwright-report' }]] : 'list',
  outputDir: '../../test-results',
  snapshotPathTemplate: '{testDir}/__screenshots__/{testFileName}/{arg}{ext}',
  use: {
    baseURL: 'http://localhost:4173',
    viewport: { width: 1000, height: 600 },
    deviceScaleFactor: 1,
    launchOptions: {
      ...(process.env.CHROMIUM_PATH ? { executablePath: process.env.CHROMIUM_PATH } : {}),
      args: ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader', '--ignore-gpu-blocklist'],
    },
    trace: 'retain-on-failure',
  },
  webServer: {
    command: 'node tools/serve.mjs 4173',
    url: 'http://localhost:4173/dist/',
    cwd: '../..',
    reuseExistingServer: !process.env.CI,
    timeout: 20_000,
  },
});
